# Applications
---
#title: DieselDC Inc.
maintainer: jovianod10@gmail.com
config_file: https://github.com/example/my-links.yaml

applications:
- name: Facebook
  team: Facebook-ReEngineer
  slack: facebook-engineering
  environments:
    staging:
      url: http://www.example.org/google-staging
      login_user: myusername
      login_password: mypassword
      notes: You can also create an account to use at https://www.example.org/live-register
    live:
      url: http://www.example.org/google-live
      notes: You can also create an account to use at https://www.example.org/staging
    qa:
      url: http://www.example.org/google-QA
      login_user: myusername
      login_password: mypassword

- name: Google
  team: Algo-Search
  slack: ask-algo-search-team
  environments:
    algorithm:
      url: https://example.org/binary
    binary:
      url: https://example.org/binary

- name: IKEA
  team: Furniture-Wiz
  slack: ask-ikea-slack
  environments:
    ivar:
      url: https://example.org/ivar
      login_user: myusername
      login_password: mypassword
    hejne:
      url: https://example.org/hejne
      notes: You can also buy your HEJNE stuff here